// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	EventID      pgtype.UUID      `json:"event_id"`
	EventPrivacy int32            `json:"event_privacy"`
	Name         string           `json:"name"`
	Description  string           `json:"description"`
	Type         string           `json:"type"`
	Department   string           `json:"department"`
	Regions      []string         `json:"regions"`
	Tags         []string         `json:"tags"`
	StartAt      pgtype.Timestamp `json:"start_at"`
}
