linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - gocyclo
    - goconst
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - godot
    - gofmt
    - gosimple
    - revive

linters-settings:
  godot:
    scope: declarations
  goimports:
    local-prefixes: github.com/thylong/bouine
  gofmt:
    simplify: false
  gocyclo:
    min-complexity: 10
  revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.3
