// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        (unknown)
// source: kpis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kpi represents a KPI
type Kpi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Target        float32                `protobuf:"fixed32,4,opt,name=target,proto3" json:"target,omitempty"`
	Day           string                 `protobuf:"bytes,5,opt,name=day,proto3" json:"day,omitempty"` // ISO 8601 format (e.g., YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kpi) Reset() {
	*x = Kpi{}
	mi := &file_kpis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kpi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kpi) ProtoMessage() {}

func (x *Kpi) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kpi.ProtoReflect.Descriptor instead.
func (*Kpi) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{0}
}

func (x *Kpi) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kpi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kpi) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Kpi) GetTarget() float32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Kpi) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type GetKpisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters (optional)
	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // The page number
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Number of kpis per page
	// Filtering parameters (optional)
	Search        string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"` // Search query for filtering kpis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKpisRequest) Reset() {
	*x = GetKpisRequest{}
	mi := &file_kpis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKpisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKpisRequest) ProtoMessage() {}

func (x *GetKpisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKpisRequest.ProtoReflect.Descriptor instead.
func (*GetKpisRequest) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{1}
}

func (x *GetKpisRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetKpisRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetKpisRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// Response message for GetKpis
type GetKpisResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kpis  []*Kpi                 `protobuf:"bytes,1,rep,name=kpis,proto3" json:"kpis,omitempty"`
	// Pagination metadata
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of kpis
	Page          int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // Current page
	PageSize      int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // Number of kpis per page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKpisResponse) Reset() {
	*x = GetKpisResponse{}
	mi := &file_kpis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKpisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKpisResponse) ProtoMessage() {}

func (x *GetKpisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKpisResponse.ProtoReflect.Descriptor instead.
func (*GetKpisResponse) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{2}
}

func (x *GetKpisResponse) GetKpis() []*Kpi {
	if x != nil {
		return x.Kpis
	}
	return nil
}

func (x *GetKpisResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetKpisResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetKpisResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetKpiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKpiRequest) Reset() {
	*x = GetKpiRequest{}
	mi := &file_kpis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKpiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKpiRequest) ProtoMessage() {}

func (x *GetKpiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKpiRequest.ProtoReflect.Descriptor instead.
func (*GetKpiRequest) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{3}
}

func (x *GetKpiRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetKpiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpi           *Kpi                   `protobuf:"bytes,1,opt,name=kpi,proto3" json:"kpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKpiResponse) Reset() {
	*x = GetKpiResponse{}
	mi := &file_kpis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKpiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKpiResponse) ProtoMessage() {}

func (x *GetKpiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKpiResponse.ProtoReflect.Descriptor instead.
func (*GetKpiResponse) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{4}
}

func (x *GetKpiResponse) GetKpi() *Kpi {
	if x != nil {
		return x.Kpi
	}
	return nil
}

type PutKpiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Target        float32                `protobuf:"fixed32,3,opt,name=target,proto3" json:"target,omitempty"`
	Day           string                 `protobuf:"bytes,4,opt,name=day,proto3" json:"day,omitempty"` // ISO 8601 format (e.g., YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKpiRequest) Reset() {
	*x = PutKpiRequest{}
	mi := &file_kpis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKpiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKpiRequest) ProtoMessage() {}

func (x *PutKpiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKpiRequest.ProtoReflect.Descriptor instead.
func (*PutKpiRequest) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{5}
}

func (x *PutKpiRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutKpiRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PutKpiRequest) GetTarget() float32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *PutKpiRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

type PutKpiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpi           *Kpi                   `protobuf:"bytes,1,opt,name=kpi,proto3" json:"kpi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutKpiResponse) Reset() {
	*x = PutKpiResponse{}
	mi := &file_kpis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutKpiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutKpiResponse) ProtoMessage() {}

func (x *PutKpiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutKpiResponse.ProtoReflect.Descriptor instead.
func (*PutKpiResponse) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{6}
}

func (x *PutKpiResponse) GetKpi() *Kpi {
	if x != nil {
		return x.Kpi
	}
	return nil
}

type DeleteKpiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKpiRequest) Reset() {
	*x = DeleteKpiRequest{}
	mi := &file_kpis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKpiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKpiRequest) ProtoMessage() {}

func (x *DeleteKpiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKpiRequest.ProtoReflect.Descriptor instead.
func (*DeleteKpiRequest) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKpiRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteKpiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKpiResponse) Reset() {
	*x = DeleteKpiResponse{}
	mi := &file_kpis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKpiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKpiResponse) ProtoMessage() {}

func (x *DeleteKpiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kpis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKpiResponse.ProtoReflect.Descriptor instead.
func (*DeleteKpiResponse) Descriptor() ([]byte, []int) {
	return file_kpis_proto_rawDescGZIP(), []int{8}
}

var File_kpis_proto protoreflect.FileDescriptor

var file_kpis_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x70,
	0x69, 0x73, 0x22, 0x69, 0x0a, 0x03, 0x4b, 0x70, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x59, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4b, 0x70, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x6b, 0x70, 0x69, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x70, 0x69,
	0x73, 0x2e, 0x4b, 0x70, 0x69, 0x52, 0x04, 0x6b, 0x70, 0x69, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x1f, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x03, 0x6b, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x6b, 0x70, 0x69, 0x73, 0x2e, 0x4b, 0x70, 0x69, 0x52, 0x03, 0x6b, 0x70, 0x69, 0x22, 0x63, 0x0a,
	0x0d, 0x50, 0x75, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x61, 0x79, 0x22, 0x2d, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x03, 0x6b, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x4b, 0x70, 0x69, 0x52, 0x03, 0x6b, 0x70,
	0x69, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x70, 0x69, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf4, 0x01, 0x0a, 0x0a, 0x4b,
	0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x4b, 0x70, 0x69, 0x73, 0x12, 0x14, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4b,
	0x70, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6b, 0x70, 0x69,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x12, 0x13, 0x2e,
	0x6b, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x70, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x50, 0x75,
	0x74, 0x4b, 0x70, 0x69, 0x12, 0x13, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x4b,
	0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6b, 0x70, 0x69, 0x73,
	0x2e, 0x50, 0x75, 0x74, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x70, 0x69, 0x12, 0x16,
	0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x70, 0x69, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x70, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x6f, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x70, 0x69, 0x73, 0x42, 0x09, 0x4b,
	0x70, 0x69, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x79, 0x6c, 0x6f, 0x6e, 0x67, 0x2f, 0x72,
	0x66, 0x74, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x4b, 0x58, 0x58, 0xaa, 0x02, 0x04, 0x4b, 0x70, 0x69,
	0x73, 0xca, 0x02, 0x04, 0x4b, 0x70, 0x69, 0x73, 0xe2, 0x02, 0x10, 0x4b, 0x70, 0x69, 0x73, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x04, 0x4b, 0x70,
	0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kpis_proto_rawDescOnce sync.Once
	file_kpis_proto_rawDescData = file_kpis_proto_rawDesc
)

func file_kpis_proto_rawDescGZIP() []byte {
	file_kpis_proto_rawDescOnce.Do(func() {
		file_kpis_proto_rawDescData = protoimpl.X.CompressGZIP(file_kpis_proto_rawDescData)
	})
	return file_kpis_proto_rawDescData
}

var file_kpis_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kpis_proto_goTypes = []any{
	(*Kpi)(nil),               // 0: kpis.Kpi
	(*GetKpisRequest)(nil),    // 1: kpis.GetKpisRequest
	(*GetKpisResponse)(nil),   // 2: kpis.GetKpisResponse
	(*GetKpiRequest)(nil),     // 3: kpis.GetKpiRequest
	(*GetKpiResponse)(nil),    // 4: kpis.GetKpiResponse
	(*PutKpiRequest)(nil),     // 5: kpis.PutKpiRequest
	(*PutKpiResponse)(nil),    // 6: kpis.PutKpiResponse
	(*DeleteKpiRequest)(nil),  // 7: kpis.DeleteKpiRequest
	(*DeleteKpiResponse)(nil), // 8: kpis.DeleteKpiResponse
}
var file_kpis_proto_depIdxs = []int32{
	0, // 0: kpis.GetKpisResponse.kpis:type_name -> kpis.Kpi
	0, // 1: kpis.GetKpiResponse.kpi:type_name -> kpis.Kpi
	0, // 2: kpis.PutKpiResponse.kpi:type_name -> kpis.Kpi
	1, // 3: kpis.KpiService.GetKpis:input_type -> kpis.GetKpisRequest
	3, // 4: kpis.KpiService.GetKpi:input_type -> kpis.GetKpiRequest
	5, // 5: kpis.KpiService.PutKpi:input_type -> kpis.PutKpiRequest
	7, // 6: kpis.KpiService.DeleteKpi:input_type -> kpis.DeleteKpiRequest
	2, // 7: kpis.KpiService.GetKpis:output_type -> kpis.GetKpisResponse
	4, // 8: kpis.KpiService.GetKpi:output_type -> kpis.GetKpiResponse
	6, // 9: kpis.KpiService.PutKpi:output_type -> kpis.PutKpiResponse
	8, // 10: kpis.KpiService.DeleteKpi:output_type -> kpis.DeleteKpiResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kpis_proto_init() }
func file_kpis_proto_init() {
	if File_kpis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kpis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kpis_proto_goTypes,
		DependencyIndexes: file_kpis_proto_depIdxs,
		MessageInfos:      file_kpis_proto_msgTypes,
	}.Build()
	File_kpis_proto = out.File
	file_kpis_proto_rawDesc = nil
	file_kpis_proto_goTypes = nil
	file_kpis_proto_depIdxs = nil
}
