name: Rft-backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Cache dependencies for each module
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.sum', matrix.module)) }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: |
          go mod tidy

      # Build the Binary
      - name: Build Go Binary
        run: |
          go build -o build/example ./cmd

      # Verify Build Success
      - name: Check if binary exists
        run: |
          cd build/
          if [ ! -f "example" ]; then
            echo "Binary not found!"
            exit 1
          fi

      # Run tests
      - name: Run tests
        run: |
          go test ./...
